### ISSUE TITLE
Adding Game View

### ISSUE THREAD

**Issue by dominicfraser** [johnny2194/TableTennisApp#19]
When new db structure is merged in adding a game will break as there are new values needed by the game class.

**Comment by dominicfraser** [comment]
Remember to make a new branch.  To commit and push often so that others can see what is happening (merge to development if something is working so others can integrate), and to pull down every time you switch branch/come back to computer.

View exists for adding a game but does not work with new database structure.  

It has to save quite a lot of information, not all of which is explicitly entered by the player, do this slowly and make sure it saves everything correctly, (check in admin view where you will be able to see everything(once thats done) as if it does not then future stats will all break.

NOT Update or Delete as these can only be handled in Admin view.

Layout/nav will be handled in a separate issue.

Remember to make a new branch.  To commit and push often so that others can see what is happening (merge to development if you are confident something is working and won't break other things so others can integrate), and to pull down every time you switch branch/come back to computer.

**Comment by eoghanscrowley** [comment]
I've fixed this in latest pull request
